# Generated by Django 5.1.7 on 2025-03-27 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_charge_type', models.CharField(choices=[('flat', 'Flat Fee'), ('percentage', 'Percentage')], default='flat', help_text='Type of charge per basket (flat fee or percentage)', max_length=10)),
                ('basket_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='The charge per basket, based on the charge type', max_digits=10)),
                ('delivery_charge_per_km', models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery charge per kilometer', max_digits=10)),
                ('threshold_distance_km', models.DecimalField(decimal_places=2, default=0.0, help_text='Threshold distance for additional delivery charges (in km)', max_digits=10)),
                ('additional_charge_per_km', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional charge per km beyond the threshold distance', max_digits=10)),
                ('maximum_distance_km', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum distance for delivery (in km)', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the delivery partner', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Delivery partner active?')),
                ('store_config', models.ForeignKey(help_text='delivery partner', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partners', to='config.storefrontconfiguration')),
            ],
        ),
    ]
