# Generated by Django 5.1.7 on 2025-03-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='subaccount_code',
            field=models.CharField(default=None, help_text='Subaccount code for transactions', max_length=10),
        ),
    ]
