# Generated by Django 5.1.7 on 2025-03-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_store_description_alter_store_subaccount_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartner',
            name='store_config',
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='account_number',
            field=models.CharField(default=None, help_text='Bank account number for payments', max_length=15),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='settlement_bank',
            field=models.CharField(choices=[('140', 'ABSA'), ('151', 'FNB'), ('157', 'Nedbank'), ('163', 'Standard')], default='140', help_text='Bank code for payment', max_length=10),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='subaccount_code',
            field=models.CharField(default=None, help_text='Subaccount code for transactions', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='settlement_bank',
            field=models.CharField(choices=[('140', 'ABSA'), ('151', 'FNB'), ('157', 'Nedbank'), ('163', 'Standard')], default='140', help_text='Bank code for settlement', max_length=10),
        ),
    ]
