# Generated by Django 5.1.7 on 2025-03-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_alter_store_description_alter_store_subaccount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypartner',
            name='subaccount_code',
            field=models.CharField(default=None, help_text='Subaccount code for transactions', max_length=100, null=True),
        ),
    ]
