# Generated by Django 5.1.7 on 2025-04-03 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_alter_deliverypartner_subaccount_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Order number', max_length=100)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Transferred', 'Transferred'), ('Failed', 'Failed')], default='Pending', help_text='Status of the delivery charge', max_length=15)),
                ('user_Name', models.CharField(help_text='User name', max_length=100)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance traveled in km', max_digits=10)),
                ('total_amount', models.IntegerField(help_text='Order Total in cents')),
                ('delivery_charge', models.IntegerField(help_text='Delivery charge in cents')),
                ('delivery_partner', models.ForeignKey(help_text='Delivery partner', on_delete=django.db.models.deletion.CASCADE, to='config.deliverypartner')),
            ],
        ),
    ]
